# vim: set ft=yaml ts=2 expandtab:
---

- name: run converge from default scenario
  import_playbook: ../default/converge.yml

- name: converge local repo and jobs
  hosts: client_group
  environment:
    http_proxy: http://{{ groups['proxy_group'][0] }}:3128
    https_proxy: http://{{ groups['proxy_group'][0] }}:3128
  roles:
    - role: mafalb.restic.repo
      repo: localrepo
      url: /tmp/localrepo
      restic_repo_local_group: bin
    - role: mafalb.restic.job
      job: localjob1
      repo: localrepo
      restic_nice: ionice -c2 nice -n +19
      paths:
        - /etc
      restic_tags:
        - test
        - etc
    - role: mafalb.restic.job
      job: localjob2
      repo: localrepo
      dest: /tmp/restic.localrepo.localjob2
      paths:
        - /etc
      exclude:
        - /mnt/whatever
        - /whatever
        - /

    - role: mafalb.restic.repo
      repo: forgetit
      url: /tmp/forgetit
      restic_forget:
        flags:
          keep-within: 1y
          keep-daily: 365
        prune: true
        check: true
        schedule:
          oncalendar: daily

    - role: mafalb.restic.repo
      repo: pruneit
      url: /tmp/pruneit
      restic_forget:
        flags:
          keep-within: 1y
          keep-daily: 365
        schedule:
          oncalendar: daily
      restic_prune:
        check: true
        schedule:
          oncalendar: weekly

    - role: mafalb.restic.repo
      repo: checkit
      url: /tmp/checkit
      restic_forget:
        flags:
          keep-within: 1y
          keep-daily: 365
        schedule:
          oncalendar: daily
          delay: 2h32m
      restic_prune:
        check: true
        schedule:
          oncalendar: weekly
          delay: 2h33m
      restic_check:
        schedule:
          oncalendar: weekly

    - role: mafalb.restic.repo
      repo: checkit2
      url: /tmp/checkit2
      restic_check:
        schedule:
          oncalendar: weekly
          delay: 1h

...
