# vim: set ft=yaml ts=2 expandtab:
---

namespace: mafalb
name: restic
version: 0.1.0
readme: README.md

authors:
- Markus Falb <markus.falb@mafalb.at>

description: Ansible collection mafalb.restic

license:
- GPL-3.0-or-later

tags:
- restic
- backup

dependencies:
  "mafalb.copr": ">=0.1.0"

repository: https://github.com/mafalb/ansible-collection-restic
documentation: https://github.com/mafalb/ansible-collection-restic
homepage: https://github.com/mafalb/ansible-collection-restic
issues: https://github.com/mafalb/ansible-collection-restic/issues

...
