# vim: set ft=yaml ts=2 expandtab:
---

# copr repo is only necessary if restic is not available from OS.
#
- name: create copr_group
  hosts: client_group
  environment:
    http_proxy: http://{{ groups['proxy_group'][0] }}:3128
    https_proxy: http://{{ groups['proxy_group'][0] }}:3128
  tasks:
    - name: group by
      group_by:
        key: copr_group
      when:
        - ansible_os_family in ['RedHat','Rocky']
        - ansible_os_family != 'Fedora'


- name: install copr repo
  hosts: copr_group
  environment:
    http_proxy: http://{{ groups['proxy_group'][0] }}:3128
    https_proxy: http://{{ groups['proxy_group'][0] }}:3128
  roles:
    - role: mafalb.copr.plugin
    - role: mafalb.copr.repo
      repo: copart/restic


- name: install restic
  hosts: client_group
  environment:
    http_proxy: http://{{ groups['proxy_group'][0] }}:3128
    https_proxy: http://{{ groups['proxy_group'][0] }}:3128
  roles:
    - role: mafalb.restic.install

...
