# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge proxy
  hosts: t_proxy
  roles:
  - role: mafalb.squid.server

- name: Converge restic
  hosts: all,!t_proxy
  environment:
    http_proxy: http://t_proxy:3128
    https_proxy: http://t_proxy:3128
  roles:

  - role: mafalb.restic.pkg_mgr
  - role: mafalb.restic.install

  - role: mafalb.restic.repo
    repo: ci_generated_password
    url: /tmp/ci_generated_password
    restic_repo_local_group: bin

  - role: mafalb.restic.job
    job: test
    repo: ci_generated_password
    restic_nice: ionice -c2 nice -n +19
    paths:
    - /etc
    restic_tags:
    - test
    - etc

  - role: mafalb.restic.job
    job: non_default_backup_script
    repo: ci_generated_password
    dest: /tmp/restic.non_default_backup_script
    paths:
    - /etc
    exclude:
    - /mnt/whatever
    - /whatever
    - /

...
