# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge proxy
  hosts: t_proxy
  roles:
  - role: mafalb.squid.server

- name: Converge
  hosts: all,!t_proxy
  environment:
    http_proxy: t_proxy:3128
    https_proxy: t_proxy:3128
  roles:

  - role: mafalb.copr.plugin
    when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
    - ansible_distribution_major_version is not version('6','==')

  - role: mafalb.restic.pkg_mgr
    when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'

  - role: mafalb.restic.install

  - role: mafalb.restic.repo
    repo: ci_generated_password
    url: /tmp/ci_generated_password

  - role: mafalb.restic.job
    job: test
    repo: ci_generated_password
    paths:
    - /etc

...
