# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy
  options:
    role-file: idontexist.yml   # avoid warning while running molecule
    requirements-file: molecule/default/requirements.yml

driver:
  name: ${CI_DRIVER:-podman}

lint: |
  set -e
  ! grep -r "no_log: false" .
  ansible-lint -v
  ansible-lint -v roles/*/vars/*.yml
  flake8 -v

platforms:

- name: ${CI_HOSTNAME:-ci-rocky8}
  image: ${CI_IMAGE:-quay.io/rockylinux/rockylinux:8}
  command: /lib/systemd/systemd
  network_mode: bridge
  docker_networks:
    - name: molecule-internal
      internal: true
  networks:
    - name: molecule-internal
  devices:
    - /dev/fuse:/dev/fuse:rwm
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
    - /run
    - /run/lock
    - /tmp
  capabilities:
    - SYS_ADMIN
  privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}
  groups:
    - ci_group

- name: ci-proxy
  image: quay.io/rockylinux/rockylinux:8
  command: /lib/systemd/systemd
  network_mode: bridge
  docker_networks:
  - name: molecule-internal
    internal: true
  - name: moldecule-external
  networks:
  - name: molecule-external
  - name: molecule-internal
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /run
  - /tmp
  capabilities:
  - SYS_ADMIN
  privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}
  groups:
    - proxy_group

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
  lint:
    name: ansible-lint

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
