# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  ! grep -r "no_log: false" .
  yamllint .
  ansible-lint -v roles/* molecule/default/converge.yml molecule/default/verify.yml galaxy.yml
  ansible-lint -v roles/*/vars/*.yml
  flake8 -v

platforms:

- name: t_${CI_CONTAINER_IMAGE:-centos}${CI_CONTAINER_TAG:-7}
  image: ${CI_CONTAINER_IMAGE:-centos}:${CI_CONTAINER_TAG:-7}
  docker_networks:
  - name: molecule-internal
    internal: true
  networks:
  - name: molecule-internal
  devices:
  - /dev/fuse:/dev/fuse:rwm

- name: t_proxy
  image: centos:7
  command: /lib/systemd/systemd
  dockerfile: Dockerfile-systemd.j2
  docker_networks:
  - name: molecule-internal
    internal: true
  networks:
  - name: molecule-external
  - name: molecule-internal
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /run
  - /tmp
  capabilities:
  - SYS_ADMIN
  privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}

provisioner:
  name: ansible
  playbooks:
    docker:
      create: create.yml
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
  lint:
    name: ansible-lint
  env:
    ANSIBLE_COLLECTIONS_PATHS: "../../../../..:~/.ansible/collections"

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
