# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify
  hosts: all,!t_proxy
  tasks:
  - name: restic is executable
    command: restic --help
    changed_when: false

  - name: init a repository
    command: restic.ci_generated_password init
    args:
      creates: /tmp/ci_generated_password/config

  - name: backup # noqa 301
    command: restic.ci_generated_password.test

  - name: backup script is present
    file:
      path: /usr/local/bin/restic.ci_generated_password.test

  - name: backup through non default backup script # noqa 301
    command: bash /tmp/restic.non_default_backup_script

  - name: non default backup script is present
    file:
      path: /tmp/restic.non_default_backup_script

  - name: fusermount is present
    file:
      path: /bin/fusermount
...
