# vim: set ft=yaml ts=2 expandtab:
---

- name: Verify
  hosts: all,!t_proxy

  tasks:

  - name: restic is executable
    command: restic --help
    changed_when: false

  - name: global exclude file is not executable
    shell: |
      set -o pipefail
      ls -l /etc/restic/exclude.global.cfg | grep -e '...-..-..-'
    changed_when: false
    args:
      executable: /bin/bash

  - name: init a repository
    command: restic.ci_generated_password init
    args:
      creates: /tmp/ci_generated_password/config

  - name: backup # noqa 301
    command: restic.ci_generated_password.test

  - name: backup script is present # noqa 208
    file:
      path: /usr/local/bin/restic.ci_generated_password.test

  - name: backup through non default backup script # noqa 301
    command: bash /tmp/restic.non_default_backup_script

  - name: non default backup script is present # noqa 208
    file:
      path: /tmp/restic.non_default_backup_script

  - name: check excludes
    command: grep -- {{ item }} /tmp/restic.non_default_backup_script
    changed_when: false
    loop:
    - '"^ --exclude /whatever"'
    - '"^ --exclude /mnt/whatever"'

  - name: / is not in excludes
    shell: grep -- '--exclude /' /tmp/restic.non_default_backup_script || true
    changed_when: false

  - name: 2 excludes are present
    shell: test $(grep -c -- "--exclude " /tmp/restic.non_default_backup_script) = "2"
    changed_when: false

  - name: count words in result from templating
    shell: test $(bash -x /tmp/restic.non_default_backup_script 2>&1|grep +|wc -w) = "10"

  - name: fusermount is present # noqa 208
    file:
      path: /bin/fusermount

...
