# vim: set ft=yaml ts=2 expandtab:
---

- name: get OS specific variables
  ansible.builtin.include_vars:
    file: "{{ _item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  - default.yml
  loop_control:
    loop_var: _item

- block:

  - name: create directory for repo "{{ repo|mandatory }}"
    file:
      path: /etc/restic.repos.d/{{ repo|mandatory }}
      state: directory
      mode: 0755

  - name: create environment file for repo "{{ repo }}"
    template:
      src: "{{ t.src }}"
      dest: "{{ t.dest }}"
      backup: true
      mode: 0644
    loop:
      - src: env.j2
        dest: /etc/restic.repos.d/{{ repo }}/env
    loop_control:
      loop_var: t

  - name: systemd units for forget/prune/check are present
    block:
      - name: systemd units are present
        template:
          src: "{{ unit }}.j2"
          dest: /etc/systemd/system/restic.{{ repo }}-{{ unit }}
          mode: '0644'
        loop:
          - prune.service
          - prune.timer
        loop_control:
          loop_var: unit
        notify:
          - systemd daemon-reload
          - restart prune.timer

      - name: prune timer is enabled/disabled
        systemd:
          name: restic.{{ repo }}-prune.timer
          state: started
          enabled: "{{ true if restic_retention_time is defined else false }}"
    when: restic_has_keep_within|default(true)

  - name: cachedir is present
    file:
      path: "{{ cachedir|default(restic_default_cachedir) }}"
      state: directory
      mode: 00700
      owner: root

  - name: write password file for repo "{{ repo }}"
    copy:
      content: "{{ password }}"
      dest: /etc/restic.repos.d/{{ repo }}/password
      backup: true
      mode: 0440
      force: false
    when: password is defined

  - name: create a new password for repo "{{ repo }}"
    copy:
      content: "{{ lookup('password', '/dev/null') }}"
      dest: /etc/restic.repos.d/{{ repo }}/password
      group: "{{ restic_repo_local_group|default(omit) }}"
      backup: true
      force: false
      mode: '440'

  # mode and ownership maybe wrong
  - name: create a new password for repo "{{ repo }}"
    file:
      dest: /etc/restic.repos.d/{{ repo }}/password
      group: "{{ restic_repo_local_group|default(omit) }}"
      mode: '440'

  - name: wrapper script is present for repo "{{ repo }}"
    template:
      src: wrapper.sh.j2
      dest: /usr/local/bin/restic.{{ repo }}
      backup: true
      mode: 0755
      validate: bash -n %s

  when: restic_repo_state == 'present'

- block:

  - name: absent
    file:
      path: "{{ _item }}"
      state: absent
    loop:
    - /usr/local/bin/restic.{{ repo }}
    - /etc/restic.repos.d/{{ repo }}
    loop_control:
      loop_var: _item

  when: restic_repo_state == 'absent'

...
