# vim: set ft=yaml ts=2 expandtab:
---

- name: copr repo for EL6
  copy:
    src: copr.repo
    dest: /etc/yum.repos.d/restic.repo
    backup: true
  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution_major_version is version('6','==')

- name: copr repo for EL7 and later
  include_role:
    name: mafalb.copr.repo
  vars:
    repo: copart/restic
  when:
  - ansible_os_family == 'RedHat'
  - ansible_distribution_major_version is not version('6','==')
  - ansible_distribution != 'Fedora'

...
