# vim: set ft=yaml ts=2 expandtab:
---

- name: create directory for repo "{{ repo|mandatory }}"
  file:
    path: /etc/restic.repos.d/{{ repo|mandatory }}
    recurse: true

- name: create environment file for repo "{{ repo }}"
  template:
    src: env.j2
    dest: /etc/restic.repos.d/{{ repo }}/env
    backup: true

- name: write password file for repo "{{ repo }}"
  copy:
    content: "{{ password }}"
    dest: /etc/restic.repos.d/{{ repo }}/password
    backup: true
    mode: "0440"
  when: repic_repo_password is defined

- name: create a new password for repo "{{ repo }}"
  copy:
    content: "{{ lookup('password', '/dev/null') }}"
    dest: /etc/restic.repos.d/{{ repo }}/password
    backup: true
    force: false
    mode: "0440"

- name: wrapper script is present for repo "{{ repo }}"
  template:
    src: wrapper.sh.j2
    dest: /usr/local/bin/restic.{{ repo }}
    mode: "0755"

...
