# Copyright (c) 2020-2022 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: systemd units are present (prune)
  template:
    src: "{{ unit }}.j2"
    dest: /etc/systemd/system/restic.{{ restic_repo }}-{{ unit }}
    mode: '0644'
  loop:
    - prune.service
    - prune.timer
  loop_control:
    loop_var: unit
  register: _reg_restic_repo_systemd_unit

- name: systemd daemon-reload
  systemd:
    daemon-reload: true
  when: _reg_restic_repo_systemd_unit.results|selectattr('changed')|list

- name: prune timer is started
  systemd:
    name: restic.{{ restic_repo }}-prune.timer
    state: started
    enabled: true

...
