# vim: set ft=yaml ts=2 expandtab:
---

- name: directory for mafalb-shellscripts is present
  file:
    path: /usr/local/lib/mafalb-shellscripts
    state: directory

- name: lib.sh is present
  template:
    src: lib.sh.j2
    dest: /usr/local/lib/mafalb-shellscripts/lib.sh
    force: false

- name: restic job is present
  block:

  - name: backup script for job "{{ job }}" is present
    template:
      src: backup.sh.j2
      dest: "{{ dest|default('/usr/local/bin/restic.' + repo|mandatory + '.' + job|mandatory) }}"
      mode: "0755"
      backup: true
      validate: bash -n %s

  when: restic_job_state == 'present'

- name: restic job is absent
  block:

  - name: backup script for job "{{ job }}" is absent
    file:
      path: "{{ dest|default('/usr/local/bin/restic.' + repo|mandatory + '.' + job|mandatory) }}"
      state: absent

  when: restic_job_state == 'absent'

...
