# vim: set ft=yaml ts=2 expandtab:
---

- name: restic is installed
  package:
    name: restic

- name: /etc/restic is present
  file:
    path: /etc/restic
    state: directory

- name: file for global excludes is present
  template:
    src: "exclude.global.cfg.j2"
    dest: /etc/restic/exclude.global.cfg
    backup: true

...
