# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:
  push:
    tags-ignore:
    - '*'

  schedule:
    - cron: '40 11 * * 6'

jobs:

  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - centos6
        - centos7
        - centos8
        - fedora31
        - fedora32
        - fedora33
        - ubuntu18
        - ubuntu20
        - debian10

        ansible_version:
        - '2.10'
        - '2.9'

        include:

        - target: centos6
          image: centos
          tag: 6

        - target: centos7
          image: centos
          tag: 7

        - target: centos8
          image: centos
          tag: 8

        - target: fedora31
          image: fedora
          tag: 31

        - target: fedora32
          image: fedora
          tag: 32

        - target: fedora33
          image: fedora
          tag: 33

        - target: ubuntu18
          image: ubuntu
          tag: bionic

        - target: ubuntu20
          image: ubuntu
          tag: focal

        - target: debian10
          image: debian
          tag: buster

    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_CONTAINER_IMAGE: ${{ matrix.image }}
      CI_CONTAINER_TAG: ${{ matrix.tag }}
      CI_CONTAINER_PRIVILEGED: true
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/restic

    steps:

      - name: checkout collection
        uses: actions/checkout@v2
        with:
          path: ansible_collections/mafalb/restic

      - name: update apt cache
        run: sudo apt-get update

      - name: install dependencies
        run: ansible-galaxy collection install -r molecule/requirements.yml

      - name: update apt cache
        run: sudo apt-get update

      - name: install molecule
        run: ansible-playbook -D molecule/install_molecule.yml -e molecule_ansible_version=${{ matrix.ansible_version }}

      - name: check ansible version
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          ansible --version | grep "^ansible ${{ matrix.ansible_version }}"

      - name: run molecule default scenario
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          molecule test

      - name: run molecule uninstall scenario
        run: |
          source ~/.virtualenvs/molecule/bin/activate
          molecule test -s uninstall

...
