# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
    - cron: '40 11 * * 6'

jobs:

  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        ansible_version:
        - '2.11'
        - '2.10'
        - '2.9'

        target:
        - fedora33
        - fedora34
        - c8s
        - alma8
        - centos7
        - centos8
        - debian10
        - ubuntu18
        - ubuntu20

        include:

        - target: fedora33
          image: fedora
          tag: 33

        - target: fedora34
          image: fedora
          tag: 34

        - target: c8s
          distribution: centos
          registry: "quay.io/centos/"
          version: stream8

        - target: alma8
          distribution: almalinux
          registry: "docker.io/almalinux/"
          version: 8

        - target: centos7
          image: centos
          tag: 7

        - target: centos8
          image: centos
          tag: 8

        - target: debian10
          image: debian
          tag: buster

        - target: ubuntu18
          image: ubuntu
          tag: bionic

        - target: ubuntu20
          image: ubuntu
          tag: focal

    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_REGISTRY: ${{ matrix.registry }}
      CI_CONTAINER_IMAGE: ${{ matrix.image }}
      CI_CONTAINER_TAG: ${{ matrix.tag }}
      CI_CONTAINER_PRIVILEGED: true
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/restic

    steps:

    - name: checkout collection
      uses: actions/checkout@v2
      with:
        path: ansible_collections/mafalb/restic

    # use the github actions ansible
    #
    - name: get mafalb.ansible
      run: ansible-galaxy collection install mafalb.ansible

    # use the system ansible
    #
    - name: install molecule
      run: |
        sudo apt-get install ansible
        /usr/bin/ansible-playbook -D ~/.ansible/collections/ansible_collections/mafalb/ansible/playbooks/molecule.yml -e molecule_ansible_version=${{ matrix.ansible_version }} -t all,debug

    # use our ansible
    #
    - name: check ansible version
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        ansible --version | grep "^ansible ${{ matrix.ansible_version }}"

    - name: run molecule default scenario
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule test

    - name: run molecule uninstall scenario
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule test -s uninstall

...
