# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
    - cron: '40 11 * * 6'

jobs:

  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - fedora34
        - fedora35
        - fedora36
        - c8s
        - alma8
        - rocky8
        - centos7
        - debian10
        - ubuntu18
        - ubuntu20

        ansible_version:
        - '2.9'
        - '2.10'
        - '2.11'

        include:
          - target: fedora36
            has_restserver: true

    env:
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1

    defaults:
      run:
        working-directory: ansible_collections/mafalb/restic

    steps:

    - name: checkout collection
      uses: actions/checkout@v2
      with:
        path: ansible_collections/mafalb/restic

    # use the github actions ansible
    #
    - name: get mafalb.ansible
      run: ansible-galaxy collection install mafalb.ansible

    # use the system ansible
    #
    - name: install molecule
      run: |
        sudo apt-get install ansible
        /usr/bin/ansible-playbook -D ~/.ansible/collections/ansible_collections/mafalb/ansible/playbooks/molecule.yml -e molecule_ansible_version=${{ matrix.ansible_version }} -t all,debug

    # use our ansible
    #
    - name: check ansible version
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        ansible --version | grep "^ansible.* ${{ matrix.ansible_version }}"

    - name: run molecule restserver scenario
      if: matrix.has_restserver 
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule -e .env-${{ matrix.target }}.yml test -s restserver

    - name: run molecule default scenario
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule -e .env-${{ matrix.target }}.yml test

    - name: run molecule uninstall scenario
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule -e .env-${{ matrix.target }}.yml test -s uninstall

...
